### ISSUE TITLE
Seconds cannot be hidden

### ISSUE THREAD

**Issue by nikolajskov** [n0shake/Clocker#65] opened 2019-07-18 06:25 UTC
Just updated to version 1.6.10 (65) and then the seconds were showing for my clocks -- they weren't before. I went to the Appearance tap in Settings to hide them by toggling "Display the time in seconds"... but the setting doesn't do anything... the seconds are still showing in both main panel and menu bar.

**Comment by MattIPv4** [comment] 2019-07-18 07:46
Can confirm, I am having the same issue.

Looks like #66 is a duplicate report of this also.

**Comment by chlab** [comment] 2019-07-18 11:02
Ah it looks like we created an issue at the same time. I also have the issue, I closed #66 because it's a duplicate.

**Comment by eanderle** [comment] 2019-07-18 14:16
Hey all, found a workaround: if you add new timezones, they will respect the seconds display setting. So re-add your existing timezones, and delete the previous ones.

Thank you @n0shake for such a wonderful tool! Hopefully we can get the issue resolved.

**Comment by n0shake** [comment] 2019-07-18 16:04
Yikes, can you see if toggling seconds from the overflow menu helps?
<img width="721" alt="Screen Shot 2019-07-18 at 9 04 03 AM" src="https://user-images.githubusercontent.com/8280282/61473340-127f2d80-a93b-11e9-8c80-4ca4c4460a5b.png">

**Comment by MattIPv4** [comment] 2019-07-18 16:06
@n0shake Can confirm that works :)

**Comment by krc** [comment] 2019-07-18 20:35
also having this issue, as well as the 12/24 hour issue I just opened.

**Comment by nikolajskov** [comment] 2019-07-19 06:00
@n0shake From the overflow menu for my clocks I could see that "DISPLAY SECONDS" were all set to "Yes". Is that a new setting in this version? I have never used it; only the global setting. Anyways, setting it to "No" in the overflow menu hides the seconds for that clock. Also, setting it to "Global" then uses the global setting for that particular clock. The global setting controls the individual clocks set to "Global". So actually everything works apart from existing clocks getting "DISPLAY SECONDS" set to "Yes" on upgrade.

**Comment by chlab** [comment] 2019-07-19 07:11
I can confirm the same behavior as @nikolajskov. So it seems the only bug is that the individual clocks suddenly had their _seconds_ setting set to yes, instead of global.

**Comment by alexndreazevedo** [comment] 2019-07-19 12:45
@n0shake Thanks for providing the information for it.

It seems that the only issue is usability. It may lead the user to mistakenly ignore that it includes global settings and settings per timezone.

Would be good to introduce an icon informing that there are these two settings. I'll create a PR for it.

**Comment by lookfirst** [comment] 2019-07-21 03:39
> It seems that the only issue is usability.

I just ran into this and yes, totally confused me. I 'get it' now, but I feel like this is over doing it on the UX complexity to be able to set showing seconds on a per item basis in the drop down.

I'd be happy with simplifying it to:

In the menubar, show/hide seconds.
In the drop down, show/hide seconds for all.

**Comment by n0shake** [comment] 2019-07-21 18:06
@lookfirst Fair point! There's an added layer of complexity added through the per timezone based customization options, but it serves and addresses an important use-case for many (including me). Since I deal with servers and sometimes require seconds-level precision, I can enable seconds for my UTC timezone (and not for the rest of the 6 timezones). This also reduces battery and CPU usage.

I'll try and word the over-flow menu features in a more descriptive way to avoid the confusion in a future version. Thanks for the feedback!

**Comment by MattIPv4** [comment] 2019-07-21 21:14
@n0shake If you're aiming for that level of customisability, could I suggest you do the same with date/day settings? I'd like to display seconds, day & date for my local TZ but only hour/min for remote TZs?

**Comment by lookfirst** [comment] 2019-07-24 04:31
@n0shake Latest update just applied and reset all my seconds settings. Heh. =)

**Comment by n0shake** [comment] 2019-07-25 00:48
Anybody else seeing this issue in 1.6.12? If not, I'll go ahead and close it :)

**Closed** 2019-07-26 14:20 UTC
