### ISSUE TITLE
Time format does not change menubar display from 24-hr time

### ISSUE THREAD

**Issue by AutonomousEngineer** [n0shake/Clocker#82] opened 2021-02-01 19:26 UTC
Updated to 20.10.04 (88) via App Store on macOS 10.15.7. Time format selected never changes the time format displayed. I am stuck with 24-hr time when trying to set 12-hr w/ AM/PM display.

![Screen Shot 2021-02-01 at 2 24 08 PM](https://user-images.githubusercontent.com/3311455/106507630-52fcb880-6499-11eb-8f12-7620d37dcf9e.png)

**Comment by n0shake** [comment] 2021-02-01 19:41
The issue is the timezone format might be overridden at the local/timezone level which means the preference you set in Preferences doesn't get respected.

I'll push out a fix by EOD.

**Comment by n0shake** [comment] 2021-02-02 16:08
Fixed in v21.02.02.

**Closed by n0shake** 2021-02-02 16:08 UTC
