### ISSUE TITLE
Clocker.app.zip not opening.

### ISSUE THREAD

**Issue by Trevor-** [n0shake/Clocker#89] opened 2021-02-10 14:03 UTC
The Clocker.app.zip from the release page https://github.com/n0shake/Clocker/releases/tag/v21.03.01 does not open.
After unzipping I get _The application "Clocker" can't be opened_. Right-clicking on then clicking on open doesn't help.
<img width="420" alt="2021-02-10_15-47-30" src="https://user-images.githubusercontent.com/7702473/107518825-24c55a00-6bb8-11eb-878d-42aaa2db0dda.png">
I'm Using Catalina on Mac Mini 2019.
Please can you check it out and upload a fixed version.
Thanks

**Comment by neilmartin83** [comment] 2021-02-11 15:13
I am seeing an issue with the app's code signature failing, it looks like the app bundle may have been modified after signing:

![image](https://user-images.githubusercontent.com/10920581/107656070-afbb5880-6c7b-11eb-886d-2aa3c72d9541.png)

**Comment by Daz-wallace** [comment] 2021-03-16 18:27
Hi folks,

Did you have any luck on this one?

**Comment by beret** [comment] 2021-03-16 18:55
I can still reproduce it when extracting via Archive Utility or Keka under Big Sur, but the Mac App Store works fine to install it.

**Comment by neilmartin83** [comment] 2021-04-08 14:15
Hi folks,

Did you have any luck on this one?

**Comment by Trevor-** [comment] 2021-04-09 09:08
Nope

**Comment by OkBeacon** [comment] 2021-06-08 13:37
I am getting same error when installed using HomeBrew

**Comment by vizcay** [comment] 2021-06-26 14:27
Same problem here on MacOS Mojave.

**Comment by vizcay** [comment] 2021-06-26 17:32
Custom building instructions on the README will be great also!

**Comment by n0shake** [comment] 2021-06-27 20:57
Just uploaded a new release (v21.07.01). I've personally tried downloading the release and making sure things work fine. @Trevor- can you try and let me know if it works?

**Comment by Trevor-** [comment] 2021-06-27 21:11
Thanks, @n0shake ,
Much appreciated. It is loading now but there's an issue with the time slider.
![image](https://user-images.githubusercontent.com/7702473/123559481-e87c4a00-d7a4-11eb-81d5-608599e0f9a3.png)
The button doesn't do anything.
In the old version, I have 
![image](https://user-images.githubusercontent.com/7702473/123559500-06e24580-d7a5-11eb-9bbf-5209f1433fe7.png)
which is incredibly useful for me.
Do you think that it's not working because the old version still exists? I just quit the old version and renamed it and installed the new version.

**Comment by n0shake** [comment] 2021-06-27 21:15
Appreciate the feedback!

> The button doesn't do anything.

That's because it's not a button. The scroll view will slide backwards and forwards with your trackpad or mouse. If you don't like the new scroller, you can revert to the old slider by selecting the **Legacy** option next to the "Show Future Slider" label in Preferences (attached image).

<img width="801" alt="Screen Shot 2021-06-27 at 4 14 23 PM" src="https://user-images.githubusercontent.com/8280282/123559634-d8437b00-d762-11eb-9218-78c4bf5a8f8a.png">

**Comment by Trevor-** [comment] 2021-06-27 21:23
Well, that helps a lot!
I do like the legacy slider and that is working well.
The new one is not working, i.e. not tracking my mouse or anything. It doesn't bother me but if you are available now I'd be happy if you wanted to do a quick zoom or anydesk session to see what I mean.
I will only be available for the next 10 minutes.
You can mail me if you want _contact at creative-scripts dot com_

**Comment by n0shake** [comment] 2021-06-27 21:39
Closing this because the original issue (file not opening) has been resolved!

**Closed by n0shake** 2021-06-27 21:39 UTC
