### ISSUE TITLE
Can you package this application as a Homebrew Cask?

### ISSUE THREAD

**Issue by mbigras** [n0shake/Clocker#73] opened 2019-10-02 07:04 UTC
I would love to install this application! I searched Homebrew Cask and it looks like it used to be packed but is no longer

```
$ brew search Clocker
No formula or cask found for "Clocker".
Closed pull requests:
Delete clocker.rb (https://github.com/Homebrew/homebrew-cask/pull/54474)
Clocker (https://github.com/Homebrew/homebrew-cask/pull/37724)
Update clocker - uninstall launchctl (https://github.com/Homebrew/homebrew-cask/pull/37916)
```

Can you package it as a cask? It's so much easier to automate installation without needing to fuss with the App Store.

**Comment by NathanUrwin** [comment] 2020-01-29 18:26
Duplicate of #56

**Comment by n0shake** [comment] 2020-12-07 00:45
Closing and let's continue related discussion in #56.

**Closed by n0shake** 2020-12-07 00:45 UTC
